CREATE TABLE IF NOT EXISTS `users`(
   `username` VARCHAR(100) NOT NULL,
   `password` VARCHAR(100) NOT NULL,
   PRIMARY KEY ( `username` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `carousels`(
   `id` VARCHAR(64) NOT NULL,
   `img` VARCHAR(100) NOT NULL,
   `title` VARCHAR(100) NOT NULL,
   `caption` LONGTEXT NOT NULL,
   PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `restaurants`(
   `id` VARCHAR(64) NOT NULL,
   `name` VARCHAR(100) NOT NULL,
   `level` INTEGER NOT NULL,
   `area` VARCHAR(100) NOT NULL,
   `imgGroup` VARCHAR(100) NOT NULL,
   PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `sweet_categorys`(
   `id` VARCHAR(64) NOT NULL,
   `title` VARCHAR(100) NOT NULL,
   PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `sweet_infos`(
   `id` VARCHAR(64) NOT NULL,
   `title` VARCHAR(100) NOT NULL,
   `thumb` VARCHAR(100) NOT NULL,
   `caption` LONGTEXT NOT NULL,
   `desc` LONGTEXT NOT NULL,
   `category_id` VARCHAR(100) NOT NULL,
   `area_id` VARCHAR(100) NOT NULL,
   `difficulty` INTEGER NOT NULL,
   `restaurant_id` VARCHAR(100) NOT NULL,
   PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


